version: "3"

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file: .env
    ports:
      - 192.168.31.101:5432:5432

volumes:
  db_data:
