apiVersion : apps/v1
kind: Deployment
metadata:
  name: django-app
  namespace: edu-trusting-bartik
spec:
  replicas: 1
  selector:
    matchLabels:
      project: django-app
  template:
    metadata:
      labels:
        project: django-app
    spec:
      containers:
      - name: django-app
        envFrom:
        - configMapRef:
            name: django-config
        image: nstonic/test_django_app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: django-service
  namespace: edu-trusting-bartik
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30241
  selector:
    project: django-app
  type: NodePort