apiVersion : apps/v1
kind: Deployment
metadata:
  name: django
  labels:
    app: django-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: django
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: django
        app.kubernetes.io/component: web
    spec:
      containers:
      - name: web
        envFrom:
        - configMapRef:
            name: django-config
        image: web
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: django-service
  labels:
    env: prod
spec:
  selector:
    app.kubernetes.io/name: django
    app.kubernetes.io/component: web
  type: NodePort
  externalIPs:
  -  192.168.49.55
  ports: 
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30036
    protocol: TCP
