apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrate
  namespace: edu-trusting-bartik
spec:
  ttlSecondsAfterFinished: 1
  template:
    spec:
      containers:
      - name: migrate
        image: django-app
        imagePullPolicy: IfNotPresent
        envFrom:
          - configMapRef:
              name: django-config
        command: ['python', 'manage.py', 'migrate', '--noinput']
      restartPolicy: Never
  backoffLimit: 4