apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-pv
  namespace: edu-trusting-bartik
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"