apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pvc
  namespace: edu-trusting-bartik
spec:
  storageClassName: csi-ceph-hdd-gz1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi